# Couchbase FHIR CE Configuration
# This file can be used to automatically configure the application on startup

connection:
  connectionString: "couchbase://localhost"
  username: "Administrator"
  password: "password"
  serverType: "Server" # "Server" or "Capella"
  sslEnabled: false

fhir:
  profile: "US Core"
  endpoint: "/fhir/demo"
  version: "V4"

app:
  autoConnect: true
  showConnectionDialog: false # Set to false to prevent dialog if YAML config is valid
