###################################################################################################
# Couchbase FHIR CE - User Deployment Compose File
#
# This file is the "prebuilt images" version used by the one-liner installer (install.sh).
# It intentionally:
#   * Uses pre-published container images (no local build context)
#   * Exposes ONLY port 80 via HAProxy (frontend + API routed internally)
#   * Mounts the provided config.yaml into the backend container read-only
#
# Image Tags:
#   Override by exporting FHIR_BACKEND_TAG / FHIR_FRONTEND_TAG before running install.sh, e.g.:
#     FHIR_BACKEND_TAG=v1.0.0 FHIR_FRONTEND_TAG=v1.0.0 bash install.sh ./config.yaml
#   Defaults below fall back to latest if not set.
#
# To run manually (after install.sh has laid down files):
#   docker compose pull && docker compose up -d
#
# NOTE: For local development (building images from source) use the root-level docker-compose.yaml
#       which has build contexts instead of static image references.
###################################################################################################

services:
  fhir-server:
    image: ghcr.io/couchbaselabs/couchbase-fhir-ce/fhir-server:${FHIR_BACKEND_TAG:-latest}
    mem_limit: 3g
    mem_reservation: 2g
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DEPLOYED_ENV: container
      JAVA_TOOL_OPTIONS: >-
        -Xms1g
        -Xmx2g
        -XX:MaxDirectMemorySize=512m
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=200
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/app/logs/heap.hprof
        -XX:+ExitOnOutOfMemoryError
        -Xlog:gc*:file=/app/logs/gc.log:time,uptime,level,tags:filecount=5,filesize=10M
        -XX:NativeMemoryTracking=summary
    volumes:
      - ./config.yaml:/config.yaml:ro
      # no bind mount for /app/logs in beta; use docker cp to retrieve dumps
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
    expose:
      - "8080" # internal only; not published directly
    restart: unless-stopped

  fhir-admin:
    image: ghcr.io/couchbaselabs/couchbase-fhir-ce/fhir-admin:${FHIR_FRONTEND_TAG:-latest}
    environment:
      NGINX_ENTRYPOINT_QUIET_LOGS: 1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    depends_on:
      - fhir-server
    expose:
      - "80" # internal only; served via haproxy
    restart: unless-stopped

  haproxy:
    image: haproxy:2.9-alpine
    ports:
      - "80:80" # public entry point
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - fhir-admin
      - fhir-server
    restart: unless-stopped

volumes: {}
# End of file
