apiVersion: v1
kind: PersistentVolume
metadata:
  name: couchbase-host-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/couchbase
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchbase-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: couchbase-host-pv
---
apiVersion: v1
kind: Service
metadata:
  name: couchbase
spec:
  selector:
    app: couchbase
  ports:
    - name: web
      port: 8091
      targetPort: 8091
    - name: data
      port: 11210
      targetPort: 11210
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couchbase
spec:
  selector:
    matchLabels:
      app: couchbase
  serviceName: couchbase
  replicas: 1
  template:
    metadata:
      labels:
        app: couchbase
    spec:
      containers:
        - name: couchbase
          image: couchbase:community-7.2.4
          ports:
            - containerPort: 8091
            - containerPort: 8092
            - containerPort: 8093
            - containerPort: 8094
            - containerPort: 8095
            - containerPort: 8096
            - containerPort: 11210
          env:
            - name: COUCHBASE_ADMINISTRATOR_USERNAME
              value: "Administrator"
            - name: COUCHBASE_ADMINISTRATOR_PASSWORD
              value: "password"
          volumeMounts:
            - name: couchbase-data
              mountPath: /opt/couchbase/var
          readinessProbe:
            httpGet:
              path: /ui/index.html
              port: 8091
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: couchbase-data
          persistentVolumeClaim:
            claimName: couchbase-data
