spring:
  application:
    name: backend
  config:
    import: classpath:fhir.yml

# Basic Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always

# Container-specific configuration
---
spring:
  config:
    activate:
      on-profile: prod

# Suppress error details and stack traces in production/container environments
server:
  error:
    include-stacktrace: never
    include-message: on-param
    include-binding-errors: never
    include-exception: false
  tomcat:
    accesslog:
      enabled: false

# Logging configuration for containers
logging:
  level:
    "[ca.uhn.fhir.rest.server.RestfulServer]": OFF
    "[org.apache.catalina]": WARN
    "[org.apache.catalina.connector]": OFF
    "[org.springframework.security]": WARN
    "[org.springframework.web.servlet]": WARN
    "[com.couchbase.transactions]": ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{20} - %msg%n"
